name: Cronjob
on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger for testing

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        # with:
        #  enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"  # Reads Python version from pyproject.toml

      - name: Create .env file from secret
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Create gcreds.json file from secret
        run: echo "${{ secrets.GSHEETS_CREDS }}" > gsheets_creds.json

      - name: Install dependencies
        run: uv sync

      - name: Run script
        run: uv run python main.py
